# Generated by Django 2.1.1 on 2018-11-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='f_type',
        ),
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.CharField(choices=[('Costumer', 'Costumer'), ('Stylist', 'Stylist')], default='Costumer', max_length=7),
        ),
    ]
