# Generated by Django 2.1.1 on 2018-11-26 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181124_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.CharField(choices=[('Costumer', 'Costumer'), ('Stylist', 'Stylist')], default='Costumer', max_length=8),
        ),
    ]
