# Generated by Django 2.1.3 on 2018-11-27 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181126_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='Country',
            field=models.CharField(blank=True, default='United States', max_length=15),
        ),
        migrations.AlterField(
            model_name='address',
            name='a_type',
            field=models.CharField(choices=[('Billing', 'Billing'), ('Shipping', 'Shipping'), ('Shop', 'Shop')], default='Shipping', max_length=10),
        ),
    ]
