# Generated by Django 2.1.3 on 2018-11-28 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_stylist_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stylist',
            name='image',
        ),
        migrations.RemoveField(
            model_name='stylist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Stylist',
        ),
    ]
