# Generated by Django 2.1.3 on 2018-11-28 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_gallery'),
        ('users', '0010_stylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylist',
            name='gallery',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.Gallery'),
        ),
    ]
