# Generated by Django 2.1.1 on 2018-11-20 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_auto_20181120_2337'),
        ('stylists', '0002_auto_20181119_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stylists.Stylist')),
                ('images', models.ManyToManyField(blank=True, null=True, to='images.Image')),
            ],
        ),
        migrations.AlterField(
            model_name='stylist',
            name='address',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='stylist',
            name='city',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='stylist',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stylist',
            name='state',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
