# Generated by Django 2.1.1 on 2018-11-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stylists', '0004_auto_20181120_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='name',
            field=models.CharField(default='My Gallery', max_length=150),
        ),
    ]
