# Generated by Django 2.1.1 on 2018-11-21 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stylists', '0005_gallery_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='id',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='images',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
