# Generated by Django 2.1.3 on 2018-12-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='purchased_token',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
