# Generated by Django 2.1.3 on 2018-11-29 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_auto_20181129_0027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cart_item',
            new_name='cart_items',
        ),
    ]
