# Generated by Django 2.1.1 on 2018-11-19 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('styles', '0001_initial'),
        ('stylists', '0001_initial'),
        ('products', '0002_auto_20181118_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featurette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='featurette', max_length=50)),
                ('updated', models.DateField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('style', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='styles.Style')),
                ('stylist', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='stylists.Stylist')),
            ],
        ),
    ]
