# Generated by Django 2.1.3 on 2018-12-06 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Featurette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='featurette', max_length=50)),
                ('updated', models.DateField(auto_now=True)),
                ('product', models.OneToOneField(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Product')),
                ('style', models.OneToOneField(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Variation')),
            ],
        ),
    ]
