# Generated by Django 2.1.3 on 2018-12-06 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurette',
            name='stylist',
            field=models.OneToOneField(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Stylist'),
        ),
    ]
