# Generated by Django 2.1.1 on 2018-11-08 03:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Featurette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('company', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('num_requested', models.IntegerField(default=1)),
                ('image', models.ImageField(upload_to='')),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('purchased_date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('categories', models.ManyToManyField(to='api.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Purchased',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=200)),
                ('num_requested', models.IntegerField(default=1)),
                ('image', models.ImageField(upload_to='')),
                ('duration', models.FloatField()),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('purchased_date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('categories', models.ManyToManyField(to='api.Category')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
                ('zipcode', models.IntegerField()),
                ('email', models.CharField(max_length=25)),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('stylist', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(default='here', max_length=50),
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.CharField(default='example@gmail.com', max_length=50),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='5612151234', max_length=50),
        ),
        migrations.AddField(
            model_name='purchased',
            name='styles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Style'),
        ),
        migrations.AddField(
            model_name='featurette',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Product'),
        ),
        migrations.AddField(
            model_name='featurette',
            name='style',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Style'),
        ),
        migrations.AddField(
            model_name='featurette',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='styles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Style'),
        ),
        migrations.AddField(
            model_name='contact',
            name='group',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='api.Group'),
        ),
    ]
