# Generated by Django 2.1.3 on 2018-11-28 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20181128_0452'),
        ('api', '0002_featurette'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featurette',
            name='product',
        ),
        migrations.AddField(
            model_name='featurette',
            name='product',
            field=models.OneToOneField(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Variation'),
        ),
    ]
