# Generated by Django 2.1.3 on 2018-11-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20181128_0452'),
        ('api', '0004_auto_20181128_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featurette',
            name='style',
        ),
        migrations.RemoveField(
            model_name='featurette',
            name='product',
        ),
        migrations.AddField(
            model_name='featurette',
            name='product',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
