# Generated by Django 2.1.3 on 2018-11-28 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20181128_0452'),
        ('api', '0005_auto_20181128_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurette',
            name='style',
            field=models.OneToOneField(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Variation'),
        ),
        migrations.RemoveField(
            model_name='featurette',
            name='product',
        ),
        migrations.AddField(
            model_name='featurette',
            name='product',
            field=models.OneToOneField(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Product'),
        ),
    ]
