# Generated by Django 2.1.1 on 2018-11-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181108_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
        migrations.AddField(
            model_name='cart',
            name='name',
            field=models.CharField(default='my cart', max_length=50),
        ),
        migrations.AddField(
            model_name='featurette',
            name='name',
            field=models.CharField(default='featurette', max_length=50),
        ),
        migrations.AddField(
            model_name='purchased',
            name='name',
            field=models.CharField(default='my purchase history', max_length=50),
        ),
    ]
