# Generated by Django 2.1.3 on 2018-11-28 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20181128_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurette',
            name='stylist',
            field=models.OneToOneField(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Stylist'),
        ),
    ]
