# Generated by Django 2.1.1 on 2018-11-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20181108_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='001 (123) 123-1234', max_length=18),
        ),
    ]
