# Generated by Django 2.1.1 on 2018-11-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('S', 'Style'), ('P', 'Product')], default='P', max_length=7),
        ),
    ]
