# Generated by Django 2.1.1 on 2018-11-08 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='categories',
            field=models.ManyToManyField(blank=True, default='', null=True, to='api.Category'),
        ),
    ]
