# Generated by Django 2.1.1 on 2018-11-09 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20181109_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='image',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to='staticfiles/images/'),
        ),
    ]
