# Generated by Django 2.1.1 on 2018-11-09 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20181109_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
