# Generated by Django 2.1.1 on 2018-11-09 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='file',
            new_name='image',
        ),
    ]
