# Generated by Django 2.1.1 on 2018-11-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20181111_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchased',
            name='products',
        ),
        migrations.AddField(
            model_name='purchased',
            name='products',
            field=models.ManyToManyField(blank=True, default='', to='api.Product'),
        ),
        migrations.RemoveField(
            model_name='purchased',
            name='styles',
        ),
        migrations.AddField(
            model_name='purchased',
            name='styles',
            field=models.ManyToManyField(blank=True, default='', to='api.Style'),
        ),
    ]
