# Generated by Django 2.1.1 on 2018-11-12 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20181112_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Stylist', editable=False, max_length=10)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='')),
                ('name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('phone', models.CharField(default='001 (123) 123-1234', max_length=18)),
                ('address', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
                ('zipcode', models.IntegerField()),
                ('stylist', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='featurette',
            name='user',
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(default='Product', editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='style',
            name='type',
            field=models.CharField(default='Style', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('Style', 'Style'), ('Style', 'Product')], default='P', max_length=7),
        ),
        migrations.AddField(
            model_name='featurette',
            name='stylist',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Stylist'),
        ),
    ]
