# Generated by Django 2.1.1 on 2018-11-12 22:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20181112_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='purchased_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='style',
            old_name='created_date',
            new_name='date',
        ),
        migrations.AddField(
            model_name='stylist',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='stylist',
            name='description',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
