# Generated by Django 2.1.3 on 2018-12-07 06:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='added',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
