# Generated by Django 2.1.1 on 2018-11-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20181120_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
