# Generated by Django 2.1.3 on 2018-11-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_auto_20181128_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='my gallery', max_length=200)),
                ('updated', models.DateField(auto_now=True)),
                ('images', models.ManyToManyField(to='images.Image')),
            ],
        ),
    ]
