# Generated by Django 2.1.1 on 2018-11-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0001_initial'),
        ('products', '0002_auto_20181118_1635'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='my cart', max_length=50)),
                ('products', models.ManyToManyField(blank=True, default='', to='products.Product')),
                ('styles', models.ManyToManyField(blank=True, default='', to='styles.Style')),
            ],
        ),
        migrations.CreateModel(
            name='Purchased',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='my purchase history', max_length=50)),
                ('products', models.ManyToManyField(blank=True, default='', to='products.Product')),
                ('styles', models.ManyToManyField(blank=True, default='', to='styles.Style')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
