# Generated by Django 2.1.1 on 2018-11-18 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20181118_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='user',
            name='cart',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Cart'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='001 (123) 123-1234', max_length=18),
        ),
        migrations.AddField(
            model_name='user',
            name='purchased',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Purchased'),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='user',
            name='stylist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='zipcode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
