# Generated by Django 2.1.1 on 2018-11-19 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchased',
            name='name',
            field=models.CharField(default='Purchase History', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.Image'),
        ),
    ]
