# Generated by Django 2.1.1 on 2018-11-19 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20181119_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='name',
            field=models.CharField(blank=True, default='my cart', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, default='', null=True, to='products.Product'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='styles',
            field=models.ManyToManyField(blank=True, default='', null=True, to='styles.Style'),
        ),
        migrations.AlterField(
            model_name='purchased',
            name='name',
            field=models.CharField(blank=True, default='Purchase History', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchased',
            name='products',
            field=models.ManyToManyField(blank=True, default='', null=True, to='products.Product'),
        ),
        migrations.AlterField(
            model_name='purchased',
            name='styles',
            field=models.ManyToManyField(blank=True, default='', null=True, to='styles.Style'),
        ),
    ]
