# Generated by Django 2.1.1 on 2018-11-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20181120_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchased',
            name='name',
            field=models.CharField(blank=True, default='Purchase History', max_length=50, null=True),
        ),
    ]
