# Generated by Django 2.1.1 on 2018-11-20 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_purchased_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cart',
            field=models.OneToOneField(blank=True, default=[], null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Cart'),
        ),
        migrations.AlterField(
            model_name='user',
            name='purchased',
            field=models.OneToOneField(blank=True, default=[], null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Purchased'),
        ),
    ]
