# Generated by Django 2.1.1 on 2018-11-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20181120_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchased',
            name='name',
            field=models.CharField(blank=True, default='my history', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchased',
            name='styles',
            field=models.ManyToManyField(blank=True, to='styles.Style'),
        ),
    ]
