# Generated by Django 2.1.1 on 2018-11-21 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20181121_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchased',
            name='products',
        ),
        migrations.RemoveField(
            model_name='purchased',
            name='styles',
        ),
        migrations.RemoveField(
            model_name='user',
            name='purchased',
        ),
        migrations.DeleteModel(
            name='Purchased',
        ),
    ]
