# Generated by Django 2.1.1 on 2018-11-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0003_auto_20181120_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='duration',
            field=models.IntegerField(default=15),
        ),
    ]
