# Generated by Django 2.1.1 on 2018-11-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Product', editable=False, max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('company', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('num_requested', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('purchased_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
