# Generated by Django 2.1.3 on 2018-12-07 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Style', 'Style'), ('Product', 'Product')], max_length=7)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('duration', models.IntegerField(blank=True, default=0)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('added', models.DateField(auto_now_add=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.Image')),
            ],
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('title', models.CharField(blank=True, max_length=120)),
                ('category', models.CharField(choices=[('Style', 'Style'), ('Product', 'Product')], default='Product', max_length=7)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.CharField(default='', max_length=200)),
                ('duration', models.IntegerField(blank=True, default=0)),
                ('company', models.CharField(blank=True, default='', max_length=100)),
                ('added', models.DateField(auto_now_add=True, null=True)),
                ('purchased_date', models.DateField(auto_now=True, null=True)),
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('inventory', models.IntegerField(blank=True, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.Image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.Product')),
            ],
        ),
    ]
