# Generated by Django 2.1.3 on 2018-11-27 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20181127_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='duration',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
