# Generated by Django 2.1.3 on 2018-11-28 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20181127_0317'),
        ('products', '0003_auto_20181127_0542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='purchased_date',
        ),
        migrations.AddField(
            model_name='variation',
            name='added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='category',
            field=models.CharField(choices=[('Style', 'Style'), ('Product', 'Product')], default='Product', max_length=7),
        ),
        migrations.AddField(
            model_name='variation',
            name='company',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='variation',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='variation',
            name='duration',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='variation',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.Image'),
        ),
        migrations.AddField(
            model_name='variation',
            name='purchased_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
