# Generated by Django 2.1.1 on 2018-11-20 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20181120_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='images.Image'),
        ),
    ]
